server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 60s
      routes:
        - id: user-public
          uri: lb://user-service
          predicates:
            - Path=/auth/**
        
        - id: user-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - JwtAuthenticationFilter
        
        - id: user-me
          uri: lb://user-service
          predicates:
            - Path=/users/me/**
          filters:
            - JwtAuthenticationFilter
        
        - id: subject-public
          uri: lb://subject-service
          predicates:
            - Path=/api/subject/**
            - Method=GET
          metadata:
            response-timeout: 60000
        
        - id: subject-admin
          uri: lb://subject-service
          predicates:
            - Path=/api/admin/subjects/**
          filters:
            - JwtAuthenticationFilter
          metadata:
            response-timeout: 60000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    should-on-demand-update-status-change: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}