services:
  postgres-subject:
    image: postgres:17-alpine
    container_name: postgres-subject
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - postgres_subject_data:/var/lib/postgresql/data
    networks:
      - subject-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  subject-network:
    driver: bridge

volumes:
  postgres_subject_data:
